trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    
    # Set up
    echo -e "\nSetting Up.\n"
    mkdir tmp
    echo ${PWD}
    ls -R ${PWD}
    cp -R $(dottest.project) temp/.

    docker network create demo-net
    - script: |
    
    # Set Up and write .properties file
    echo  -e "\n~~~\nSetting up and creating dottestcli.properties file.\n"
    echo $"
    parasoft.eula.accepted=true
    license.network.auth.enabled=true  
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=$(license.server.username)
    dottest.license.network.edition=server_compliance_edition
    #dottest.license.custom_edition_features=
    license.network.enabled=true
    virtualize.license.network.edition=performance_server_edition
    virtualize.license.use_network=true" >> temp/dottestcli.properties
    echo -e "\nDebug -- Verify workspace contents.\n"
    ls -R
    echo -e "\nDebug -- Verify dottestcli.properties file contents."
    cat temp/dottestcli.properties
    docker run --isolation=process --rm --mount type=bind,source="pathOnPhysicalMachine",target="/tmp/" 
    parasoft/dottest dottestcli -solution "/tmp/BankExample.sln" 
    -config "builtin://Recommended Rules" -settings "/tmp/dottestcli.properties" -report "/tmp"
- publish: /home/vsts/work/1/s/temp
  artifact: report

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml
    testRunTitle: 'Static analysis'