trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mkdir temp
    echo "current working directory: ${pwd}"
    ls -R ${PWD}

    echo "copying project to temp directory..."
    cp -R $(dottest.project) temp/.
    
    echo "verifying project files in temp:"
    ls -R temp/

    # Set Up and write .properties file
    echo  -e "\n~~~\nSetting up and creating dottestcli.properties file.\n"
    echo $"
    parasoft.eula.accepted=true
    license.network.auth.enabled=true  
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=$(license.server.username)
    dottest.license.network.edition=server_compliance_edition
    license.network.enabled=true" >> temp/dottestcli.properties
    echo -e "\nDebug -- Verify workspace contents.\n"
    ls -R
    echo -e "\nDebug -- Verify dottestcli.properties file contents."
    cat temp/dottestcli.properties
    docker run --rm \
    -v "$(pwd)/temp:/temp" \
    parasoft/dottest \
    dottestcli -settings "/temp/dottestcli.properties" -solution "/temp/BankExample.sln" -config "builtin://Recommended Rules" -report "/temp" \
    echo -e "\Done."
  displayName: 'Run Static Analysis'
- publish: /home/vsts/work/1/s/temp
  artifact: report

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml
    testRunTitle: 'Static analysis'