trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    mkdir temp
    echo "copying project to temp directory..."
    cp -R $(dottest.project) temp/.
    
    echo "
    parasoft.eula.accepted=true
    license.network.auth.enabled=true  
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=$(license.server.username)
    dottest.license.network.edition=server_compliance_edition
    license.network.enabled=true" > temp/dottestcli.properties
    echo -e "\nDebug -- Verify workspace contents.\n"
   
    echo -e "\nDebug -- Verify dottestcli.properties file contents."
   
    docker run --rm --isolation=process --mount type=bind,source=$(System.DefaultWorkingDirectory)\temp,target=c:/dockerWorkdir parasoft/dottest \
    dottestcli -solution "C:/dockerWorkdir/BankExample.sln" -config "builtin://Recommended Rules" -settings "C:/dockerWorkdir/dottestcli.properties" -report "c:/dockerWorkdir/reports" \
    echo -e "\Done."
    dir temp/reports
  displayName: 'Run Static Analysis'
- publish: /home/vsts/work/1/s/temp
  artifact: report

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml
    testRunTitle: 'Static analysis'