trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    mkdir temp
    echo "current working directory: ${pwd}"
    dir /s

    echo "copying project to temp directory..."
    xcopy /s /e $(dottest.project) temp\
    
    echo "verifying project files in temp:"
    dir temp\

    echo "Creating dottestcli.properties file..."
    echo "parasoft.eula.accepted=true" > temp/dottestcli.properties
    echo "license.network.auth.enabled=true" >> temp/dottestcli.properties
    echo "license.network.password=$(license.server.password)" >> temp/dottestcli.properties
    echo "license.network.url=$(license.server.url)" >> temp/dottestcli.properties
    echo "license.network.use.specified.server=true" >> temp/dottestcli.properties
    echo "license.network.user=$(license.server.username)" >> temp/dottestcli.properties
    echo "dottest.license.network.edition=server_compliance_edition" >> temp/dottestcli.properties
    echo "license.network.enabled=true" >> temp/dottestcli.properties
    echo -e "\nDebug -- Verify workspace contents.\n"
    ls -R
    echo -e "\nDebug -- Verify dottestcli.properties file contents."
    type temp\dottestcli.properties
    docker run --rm \
    -v "$(System.DefaultWorkingDirectory)\temp:C:\temp" \
    parasoft/dottest \
    dottestcli -settings "C:\temp\dottestcli.properties" -solution "C:\temp\BankExample.sln" -config "builtin://Recommended Rules" -report "C:\temp" \
    echo -e "\Done."
    dir temp\
  displayName: 'Run Static Analysis'
- publish: /home/vsts/work/1/s/temp
  artifact: report

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml
    testRunTitle: 'Static analysis'