trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mkdir temp
    echo ${PWD}
    ls -R ${PWD}
    cp -R $(dottest.project) temp/.
    # Set Up and write .properties file
    echo  -e "\n~~~\nSetting up and creating dottestcli.properties file.\n"
    echo $"
    parasoft.eula.accepted=true
    license.network.auth.enabled=true  
    license.network.password=$(license.server.password)
    license.network.url=$(license.server.url)
    license.network.use.specified.server=true
    license.network.user=$(license.server.username)
    dottest.license.network.edition=server_compliance_edition
    license.network.enabled=true >> temp/dottestcli.properties
    echo -e "\nDebug -- Verify workspace contents.\n"
    ls -R
    echo -e "\nDebug -- Verify dottestcli.properties file contents."
    cat temp/dottestcli.properties
    docker run --isolation=process \
    -v "$(pwd)/temp:/temp" \
    --rm \
    --mount type=bind,source="pathOnPhysicalMachine",target="/temp/" \
    parasoft/dottest dottestcli -solution "/temp/BankExample.sln" \
    -config "builtin://Recommended Rules" \
    -settings "/temp/dottestcli.properties" \
    -report "/temp"
    echo -e "\Done."
  displayName: 'Run Static Analysis'
- publish: /home/vsts/work/1/s/temp
  artifact: report

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml
    testRunTitle: 'Static analysis'