trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    mkdir temp
    echo "copying project to temp directory..."
    cp -R $(dottest.project) temp/.
    
    echo "Creating dottestcli.properties file..."
    echo "parasoft.eula.accepted=true" > temp/dottestcli.properties
    echo "license.network.auth.enabled=true" >> temp/dottestcli.properties
    echo "license.network.password=$(license.server.password)" >> temp/dottestcli.properties
    echo "license.network.url=$(license.server.url)" >> temp/dottestcli.properties
    echo "license.network.use.specified.server=true" >> temp/dottestcli.properties
    echo "license.network.user=$(license.server.username)" >> temp/dottestcli.properties
    echo "dottest.license.network.edition=server_compliance_edition" >> temp/dottestcli.properties
    echo "license.network.enabled=true" >> temp/dottestcli.properties
    
    dir $(System.DefaultWorkingDirectory)
    type temp/dottestcli.properties

    docker run --rm --isolation=process --mount type=bind,source=$(System.DefaultWorkingDirectory)\temp,target=c:/dockerWorkdir parasoft/dottest \
    dottestcli -solution "C:/dockerWorkdir/BankExample.sln" -config "builtin://Recommended Rules" -settings "C:/dockerWorkdir/dottestcli.properties" -report "c:/dockerWorkdir/reports" \
    echo -e "\Done."
    dir temp/reports
  displayName: 'Run Static Analysis'
- publish: /home/vsts/work/1/s/temp
  artifact: report

- task: PublishParasoftResults@1
  inputs:
    resultsFiles: |
      **/rep*.xml
      **/rep*.sarif
      **/coverage.xml
    testRunTitle: 'Static analysis'